# Generated by Django 3.2.13 on 2023-10-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='photo',
            new_name='image',
        ),
    ]
