# Generated by Django 3.2.13 on 2023-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20231002_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/default.png', upload_to='thumbnail/'),
        ),
    ]
