# Generated by Django 3.2.13 on 2023-10-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_remove_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/default.png', upload_to='thumbnail/'),
        ),
    ]
