# Generated by Django 3.2.13 on 2023-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/default.png', upload_to='thumbnail/', verbose_name='Thumbnail'),
        ),
    ]
