# Generated by Django 3.2.13 on 2023-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_auto_20231008_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='No description', max_length=2000, verbose_name='Description'),
        ),
    ]
