version: "3.9"

services:
  web: 
    image: pc-shop-web:latest
    ports:
      - '8000:8000'
    working_dir: /app
    volumes:
      - ./app:/app
    networks:
      - internal
  postgres:
    image: postgres:14
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    networks:
      - internal

networks:
  internal:

volumes:
  postgres_data:
